import React from 'react';

export const Shop = () => {
  return (
    <div>
      <h1>
        SHOP
      </h1>
      <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas eligendi, veniam libero deserunt alias expedita architecto reprehenderit possimus cum deleniti ea similique tempora pariatur saepe quasi dolorum dicta beatae quae!
        Totam corrupti nostrum excepturi dolor alias labore commodi, facilis, assumenda, nemo vel in ut? Velit repudiandae in quae quis quia ducimus totam, consectetur, ratione numquam voluptas nulla dolore rem id?
        Et sequi tempora praesentium quasi eligendi. Dignissimos adipisci ducimus iure fugiat, facere necessitatibus quod beatae laudantium nulla ullam odit tempora iusto! Cum dolores adipisci nam fugiat natus consectetur dolor eius.
        Veritatis reiciendis quasi perspiciatis ut nulla eos voluptates officia pariatur voluptatum! Eos, culpa. Voluptate accusantium cumque, soluta similique dignissimos nemo veritatis assumenda est doloremque. Magnam suscipit rem accusantium porro itaque?
        Architecto, aliquam voluptatum adipisci itaque quia vitae aperiam repellendus ipsa enim praesentium reiciendis vel recusandae nam maiores quae ut eligendi id odio pariatur dicta inventore. Ullam natus sed sapiente quas!
        Natus facere nemo non doloremque ipsa enim fugit. Enim impedit magni mollitia fugiat cupiditate quia officia dignissimos vel quis. Tempore quo, inventore temporibus iure voluptatum deleniti rerum voluptates harum perferendis.
        Laborum doloremque voluptas, pariatur voluptatem quas voluptate! Eius inventore doloribus neque dignissimos soluta pariatur laboriosam vitae voluptates dolor nam numquam totam omnis sint tempore perferendis error, perspiciatis officiis aliquid dolorum.
        Blanditiis doloribus asperiores porro distinctio similique facilis quidem laboriosam aliquid, deserunt eligendi aspernatur quisquam dicta id tempore et eaque aliquam ad harum libero natus ipsum enim expedita eum. Fuga, nulla!
        Reiciendis magnam ad inventore fugiat libero, porro accusantium iure odio dolores, amet sint! Iure voluptate delectus porro quos aliquid asperiores labore blanditiis autem libero dignissimos. Modi obcaecati odit assumenda eveniet.
        Dolore reiciendis est corporis sunt quam dignissimos laborum voluptas illo, quod minima ad ipsum, tenetur nisi porro. Earum praesentium, maxime inventore sint culpa possimus hic? Nisi enim quas distinctio atque?
        Ducimus aspernatur dignissimos libero rem eius magni quam? Enim illum consectetur, dolorem obcaecati, vero ratione necessitatibus quod eveniet numquam accusamus soluta veniam cupiditate molestias dolor ex. Labore dolorem accusantium quos!
        Ipsa qui fuga iure maiores molestias, nostrum laborum, laboriosam possimus ratione non quo quas quam quibusdam temporibus. Earum a assumenda sequi sit aliquam consectetur quae, magni error atque dolorem. Iste?
        Fugiat obcaecati facilis culpa dicta optio ut quas aliquam deleniti beatae perferendis aliquid cupiditate quos accusantium, excepturi officiis animi odio unde? Cum, suscipit voluptatibus. Harum expedita officiis rem dignissimos. Rerum!
        Dolores veniam commodi officiis libero. Repellat, velit quasi pariatur expedita quae iste odio ex quas ad error blanditiis fugiat quibusdam similique perferendis? Eos sunt nam ratione ipsum dolores quas reiciendis?
        Suscipit harum repellat amet placeat recusandae doloremque, ex delectus dolorum similique sint laborum eum perspiciatis deserunt asperiores soluta ea voluptate autem explicabo, quod ullam rem quis illo qui? Quibusdam, officia.
        Nobis earum mollitia commodi dolor ea officia deserunt neque dolorem perspiciatis, assumenda, alias harum ratione porro eum rerum. Impedit voluptatem sequi inventore architecto quas voluptatum sint corporis magni provident nulla?
        Quasi atque repellat cumque officia necessitatibus similique neque architecto vitae, quaerat nobis quos consequatur eum quisquam earum aut dolorum animi fuga, facere nesciunt! Alias assumenda non nostrum molestias, ipsa a.
        Dolor ab eum ratione, rem aspernatur eos obcaecati mollitia expedita voluptatem iste temporibus, doloremque dolorem amet! Voluptatem aliquam dolorum fugiat ipsa esse praesentium, id cumque. Fugit laboriosam expedita enim quia!
        Laboriosam officiis vero temporibus facere odit eaque iusto, quos ea adipisci praesentium alias, omnis eligendi officia ducimus itaque nulla possimus porro aperiam perspiciatis enim labore voluptatibus eos error consequatur. Est!
        Suscipit ducimus corrupti impedit cum delectus fuga a dolorum magnam quod, ut autem quibusdam praesentium molestiae deleniti neque iste hic quos, veritatis aperiam repudiandae minus sunt sapiente soluta dicta. Commodi!
        Consectetur sapiente, quo cupiditate fugiat laboriosam corrupti soluta aut eveniet quas, nam, facilis vitae illo repellat. Magnam, aspernatur modi, repellat nulla, dolore nemo incidunt unde vel fuga ut harum distinctio!
        Architecto id cum sapiente ullam alias autem quas odio, dolor aut, aspernatur corporis reiciendis fugiat veritatis enim distinctio iure animi voluptate dicta atque iusto sed quos! Dolor atque debitis tempora.
        Distinctio amet natus inventore eaque impedit ad magnam commodi quia, laboriosam, ipsa non voluptatum accusamus autem adipisci deleniti. Adipisci quia vel esse sunt quod illum nobis obcaecati consequuntur odit? Est?
        Tempora ratione accusamus aut nihil aliquid. Nemo expedita, facere unde, error velit ipsum nobis sunt incidunt illo laborum quasi illum aliquam asperiores repudiandae sint itaque hic quo! Commodi, natus eum.
        Nam maxime dolores reiciendis facere assumenda enim rerum quibusdam dolorem ab est consequatur ipsa molestiae culpa, autem vel vitae perspiciatis quos provident! Odio soluta nemo, non sapiente debitis explicabo ipsam.
        Aspernatur ex ab nostrum enim quas neque reiciendis, provident ratione, ea quasi inventore eveniet cum aut? Quidem accusamus dignissimos, minima culpa voluptates id at possimus totam doloremque corrupti consequuntur in!
        Quaerat delectus est atque dolorum porro provident molestias quas cum, veniam, similique quos id rerum officia beatae sit ratione, libero necessitatibus accusamus modi? Praesentium veniam obcaecati dignissimos ab ad voluptatibus?
        Adipisci dolore sint quae voluptates placeat quo ipsam possimus beatae quas facere neque quia harum, nemo suscipit reprehenderit. Laboriosam, dolores. Quia corporis unde assumenda neque consequuntur? Quos eveniet ea dolorum!
        Deserunt quaerat delectus error. Alias deserunt voluptas excepturi sapiente vitae est reprehenderit consequuntur ipsum odit quam mollitia quia facilis, delectus sed perspiciatis ea minima! Asperiores tenetur ut quae magnam nisi!
        Blanditiis voluptates similique magnam, tempore officia facilis, dolorem commodi nemo corrupti tempora, laboriosam provident iure consequuntur ut cum? Nemo excepturi exercitationem mollitia nam qui doloremque soluta commodi, voluptate explicabo voluptates.
        Commodi iusto ipsa doloribus, unde provident quod error quo aperiam sapiente voluptatum repellendus porro est laudantium quibusdam similique facilis, sint ullam reiciendis quas. Provident, quidem voluptas dolor modi aliquid eos.
        Minima molestiae, architecto suscipit recusandae adipisci fuga distinctio nobis quam amet vitae debitis reiciendis quis at qui sint reprehenderit quisquam deserunt harum! Corrupti facere commodi facilis quasi pariatur soluta tenetur?
        Rerum quisquam quasi explicabo perferendis excepturi unde velit necessitatibus modi repudiandae architecto quas amet, sapiente pariatur quis enim saepe quaerat facere doloremque minus. Harum repellat voluptatem accusamus animi, in quod!
        Eum deleniti, delectus neque praesentium maiores soluta, inventore harum, amet quam totam eius? Eaque voluptatem, rerum, officia cumque eius ullam doloremque, autem molestias excepturi quibusdam nesciunt beatae esse alias porro.
        Nemo, similique quos aperiam fuga officiis odit optio consectetur praesentium sed assumenda sunt porro voluptas, dolorem dolores ducimus cum quaerat vitae mollitia eius fugiat iste. Adipisci, tenetur. Ipsam, molestiae distinctio?
        Reprehenderit hic, deserunt nihil excepturi enim iure ex corrupti harum repellat obcaecati assumenda voluptatum necessitatibus vel quam adipisci itaque illum totam quae possimus sunt voluptate architecto ea explicabo! Corrupti, voluptates.
        Autem, officia? Nostrum, incidunt totam eum rerum nesciunt, molestias dolorem cumque eligendi blanditiis exercitationem soluta commodi temporibus ut praesentium necessitatibus enim possimus saepe quam fuga pariatur tenetur vitae dolore fugit?
        Suscipit quas veritatis, accusamus deleniti rem ratione culpa nam? Praesentium velit distinctio soluta alias, autem consequuntur maxime delectus corrupti omnis possimus repellat placeat tempora neque, nihil assumenda, ut dolorum dignissimos.
        Ea sunt odit dolorum officia, possimus cum quas praesentium, veritatis dolores est velit nostrum harum ratione voluptas atque nemo sapiente porro non temporibus? At explicabo optio, nobis dolor corporis voluptas.
        Mollitia consectetur sit officiis illo. Nihil iure omnis itaque amet alias unde! Odit, molestias. Aperiam vitae maiores mollitia odit cum nostrum unde harum praesentium consequatur veritatis autem, deleniti ex ullam!
        Perferendis modi eveniet ullam vel reiciendis facilis cumque necessitatibus quis beatae. Nam ipsum enim, earum a omnis amet soluta ipsa quasi eaque illo officia incidunt molestias voluptatibus delectus perspiciatis est.
        Sint, omnis deserunt animi aliquid eos quod quo ducimus rem fugiat! Ducimus delectus quos qui porro maiores ab voluptatum distinctio dolore enim? Unde ullam reiciendis enim aliquam sit natus tenetur!
        Perferendis sint nihil architecto ab, accusantium officiis dignissimos fugiat odit corporis dolore, a beatae minima, omnis hic doloremque voluptatum accusamus laborum pariatur? Ex nobis dolore doloremque sed debitis numquam iusto?
        Fuga laboriosam soluta ad neque rerum, magni doloremque distinctio ab nemo corrupti laborum, saepe consectetur fugit vel ut dolore natus impedit similique maiores corporis necessitatibus! Beatae eaque esse soluta libero!
        Dolores, expedita quis. Ipsum minus vero animi incidunt a accusamus consequuntur soluta expedita officiis, magnam itaque explicabo adipisci! Odio rerum eligendi harum? Alias consectetur maiores libero reprehenderit odio voluptate in!
        Corrupti hic a natus dolore dolores cupiditate, perspiciatis similique fuga repudiandae porro maiores itaque et officia fugit, officiis eius non minus numquam nostrum veniam quisquam rem voluptatem totam id. Reprehenderit.
        Tempora voluptatibus voluptate, harum itaque repudiandae, facere error laudantium nesciunt amet repellendus obcaecati excepturi nihil quis nisi exercitationem ipsam odit quasi atque explicabo? Totam culpa itaque beatae error. Aliquid, sunt.
        Corrupti accusamus doloremque eos, ipsa incidunt minus! Quas fugiat voluptatum saepe ab voluptate perferendis asperiores veritatis, suscipit iusto ad doloribus itaque nulla iure in, ut quasi! Aliquid assumenda reiciendis ipsum?
        Quibusdam nostrum ipsam, error magnam quas autem tenetur incidunt! Sint quaerat nobis optio neque assumenda totam illum, corporis odit minima maxime ipsam pariatur ad dolorum, culpa iusto, vel modi quas.
        Ullam consequatur fugit earum eligendi, deleniti ab aliquam, voluptatum sit quaerat corrupti, doloribus facere laborum itaque ex! Sequi repellat doloribus minus quia asperiores quisquam dicta tenetur distinctio hic. Sapiente, quidem!
        Molestiae non doloremque eum repellendus repellat aliquid quisquam illum adipisci! Saepe, totam excepturi dignissimos quis iure dolorum explicabo quam, nihil architecto temporibus sit inventore maxime repellat quia cumque rem iusto!
        Optio, cum? Obcaecati, ullam dicta! Asperiores a voluptas enim doloremque laboriosam facilis, fugiat voluptate vel pariatur dicta repellendus iste error corrupti. Repellendus maiores nesciunt natus facilis non suscipit ullam ea.
        Quibusdam, provident error accusantium aliquam temporibus voluptate omnis rem voluptatum at facere aliquid odio dolorum modi est soluta molestiae ex, minus in? Optio eius, blanditiis sunt nostrum doloribus hic eveniet.
        Culpa ullam porro a ipsa nisi necessitatibus accusamus esse omnis! In quod vitae unde incidunt quibusdam aspernatur blanditiis, quia amet placeat nostrum voluptates accusamus ipsum dolores molestiae soluta quos enim.
        Totam quidem cupiditate ipsam. Dolor reiciendis, aspernatur quisquam voluptate, sunt illo blanditiis sequi, itaque vitae sapiente repellat libero? Voluptas quas nulla totam dolore itaque distinctio odio sapiente doloremque iusto tempore.
        Inventore, mollitia! Quia similique illo, culpa tempore odit labore quas voluptatum dolore mollitia temporibus repellat sint explicabo totam ullam magni iusto molestias maiores, excepturi consectetur esse reprehenderit tenetur laboriosam. Blanditiis.
        Facilis unde aliquam, fuga cumque labore velit consequuntur, nobis molestiae cum nisi minima, fugiat optio accusamus totam sequi reiciendis iste? Nulla dolorem sint, totam deserunt voluptates eaque id necessitatibus? Neque.
        Magni sit dolorem culpa, dignissimos accusantium placeat ea voluptatem molestias nihil harum quas eaque magnam adipisci quaerat iure corrupti pariatur temporibus quia minus excepturi iusto. Fuga dolorum dolores veritatis quis?
        Eaque, quam modi excepturi saepe itaque blanditiis facilis numquam? Animi eaque nemo hic dolore cupiditate doloremque, deserunt modi magni facilis. Ratione nemo ipsam at atque eveniet laudantium perspiciatis quidem repellat!
        Modi eaque animi nisi accusantium tempore perferendis, provident repudiandae labore numquam vitae officiis consequuntur aliquam ab ipsum distinctio sint est. Magni quo saepe recusandae ut deleniti dicta eligendi in sit.
        Accusamus eveniet vitae exercitationem accusantium sit ducimus odit deserunt minima? Deserunt debitis odit perspiciatis qui tempore, labore recusandae, doloribus atque harum sed et quod quae corporis non error hic. Dolores.
        Sed eius numquam possimus mollitia culpa sint deleniti alias voluptates ipsum qui nostrum dolorum exercitationem ut, neque minus officia suscipit tempore facere. Blanditiis, laudantium sed adipisci perspiciatis cupiditate inventore quae!
        Amet beatae id at hic aperiam dolorem corporis rem ab eaque, distinctio vero, aliquam autem ea molestias blanditiis magni quas nihil cum iure nam voluptatem nisi laborum. Excepturi, nulla ducimus?
        Fuga, aperiam enim repellendus tempora quos aut labore laborum unde magnam, neque laudantium dicta pariatur soluta, excepturi earum praesentium natus vitae quam. Eaque dicta a, labore rerum optio pariatur vitae.
        Alias repudiandae necessitatibus molestiae pariatur! Voluptatum delectus error maiores exercitationem quaerat non, voluptate enim sapiente illo, voluptates aliquam debitis. Aperiam pariatur atque doloribus, obcaecati quos vero corrupti reprehenderit error! Amet!
        Reprehenderit impedit quas iure fugiat non perferendis a modi, aspernatur quia libero, reiciendis, quae vitae quam nobis repellat eaque molestias? Commodi pariatur ullam quasi dolore aliquam illum necessitatibus possimus autem?
        Dignissimos quidem quod ad neque, aut quasi maxime labore tenetur hic, perferendis blanditiis culpa enim ullam error sequi, quo nihil expedita odit tempora laboriosam ut suscipit pariatur ex doloribus! Eius!
        Commodi a amet recusandae vitae odit, odio aperiam iste accusantium magnam eaque, sit itaque, sed maxime tenetur repellendus cupiditate in! Ipsam, provident modi temporibus vel eaque aspernatur iste reiciendis consequatur!
        Neque, tenetur. Beatae nostrum sequi atque repellat eum, numquam optio sit eaque qui quasi voluptatum neque distinctio omnis veniam ducimus sunt voluptatem eveniet! Explicabo libero quas esse, beatae natus et!
        Repudiandae beatae quasi corporis obcaecati id, distinctio fuga deleniti esse exercitationem nihil reprehenderit quisquam ipsa autem necessitatibus molestias sapiente debitis. A nobis culpa sint quod accusamus? Labore iure asperiores cumque.
        Cum asperiores voluptates eligendi unde voluptatum. Expedita iusto voluptatum ab rerum earum consequuntur fuga? Ut nihil quibusdam ducimus deleniti facere magni necessitatibus cumque unde natus. Provident veritatis quae ad inventore?
        Voluptatem, esse aut. Ea sit natus sed quibusdam obcaecati molestiae maxime placeat numquam distinctio, dolores quis incidunt facere in tempore rerum commodi voluptas, qui necessitatibus temporibus fugiat! Sit, maiores rem?
        Laboriosam quam saepe, sit aperiam soluta facere officiis velit illum minus repellat quis corrupti cupiditate vero sapiente incidunt ipsam nam laborum voluptas magni distinctio! Eaque quis ab voluptates iusto numquam?
        Minima officia quis consequuntur hic nulla iusto, sunt ut laboriosam cupiditate libero accusamus corrupti architecto ad veritatis. Eius odit reprehenderit laudantium numquam, quia, mollitia debitis corrupti architecto ducimus, atque voluptatibus?
        Perferendis consequuntur quisquam quae ex reprehenderit. Quaerat aliquam sit optio laboriosam nam aspernatur rerum possimus numquam sint eligendi officia, temporibus minima enim maiores voluptatibus veritatis esse minus, ipsam dolorem repellendus.
        Magni laudantium eos tenetur aut, inventore necessitatibus aspernatur quas. Culpa consectetur, beatae nemo odit sed porro? Aut itaque, est, accusantium corrupti, laudantium nesciunt ex reprehenderit consequuntur adipisci voluptatibus deserunt totam!
        Facere possimus veniam unde quasi sunt alias quo dolor delectus. Illum veniam explicabo voluptatem consequatur recusandae, placeat debitis, doloremque labore similique quia perferendis cupiditate eaque voluptas dignissimos sit, deleniti ipsam?
        Voluptates alias provident distinctio vel molestiae? Consequatur obcaecati pariatur numquam ratione ad consectetur debitis reprehenderit accusamus explicabo nihil nisi culpa, magnam ipsum asperiores sapiente deserunt cumque eveniet corporis quo voluptates.
        Aperiam odio odit doloribus eos cum sint, dolore consequatur debitis officia exercitationem? Animi, tenetur labore. Et fuga, dolor hic quibusdam id asperiores rem voluptas iste fugiat dolore ex molestias reprehenderit.
        Delectus corrupti labore expedita libero, possimus dolore architecto? Quo in ullam fugiat nobis exercitationem non, sed, voluptas mollitia, ducimus expedita ab dolores aliquam atque rem numquam aspernatur consectetur natus omnis.
        Modi vitae eius officia temporibus, ea error numquam nisi maiores neque odio quam cumque expedita quasi harum totam fugit. Iste libero, voluptatum eius nesciunt aliquam maxime adipisci quas odit consequatur?
        In dignissimos rerum perferendis, odit quibusdam, exercitationem reprehenderit eaque voluptates tenetur delectus sapiente voluptas aliquid numquam veritatis libero! Veritatis placeat explicabo illum ipsa, omnis quo vero natus suscipit animi voluptatum.
        Quis beatae illum officiis optio tenetur neque quas possimus, ad perspiciatis perferendis impedit veniam cum recusandae dolorum magni quia ipsa ducimus blanditiis numquam cupiditate. Est necessitatibus eius consequuntur sunt iure?
        Dolorem alias placeat eveniet odio saepe a molestiae laboriosam suscipit libero quam, in quisquam. Praesentium reprehenderit corporis aspernatur, doloribus reiciendis numquam ducimus debitis laboriosam nihil itaque quidem sint, recusandae saepe?
        Ipsa ut cumque cupiditate accusamus molestiae voluptatum officiis impedit sit atque nihil eos suscipit enim, facilis sint recusandae placeat libero veritatis aut, illo tenetur maxime blanditiis. Id adipisci quam laudantium.
        Eveniet ipsam voluptatum sint animi quidem, unde tempore beatae? Porro assumenda, ut nisi, libero, voluptate quod facere cumque quidem exercitationem modi provident laboriosam. Ducimus in quaerat consequuntur a, necessitatibus libero.
        Tempora doloribus voluptatem, eligendi veritatis aperiam animi qui quos deserunt porro? Cum nam dignissimos nisi ducimus, delectus cumque praesentium odit. Officia neque asperiores eligendi, mollitia eos ex dolores cum impedit.
        Sapiente nisi perspiciatis et recusandae magni animi blanditiis libero. Vitae esse nisi ipsam quod laboriosam obcaecati nemo quo omnis. Dolorum sapiente nemo adipisci tenetur quam dolore enim aperiam fuga explicabo?
        Magnam repellat minus aperiam? Atque, dolorum? Voluptatum, obcaecati unde. Ducimus repellat aliquid beatae atque illum aspernatur nihil, quasi tempora eum nisi magni ab delectus veritatis placeat nam quaerat inventore possimus.
        Nostrum ullam expedita deleniti at neque iusto vel modi repellat! Impedit voluptatem natus voluptatibus amet illum accusamus animi aliquam maxime cupiditate, dolor similique beatae at! Ea consequuntur explicabo nostrum libero?
        Quaerat, amet molestias! Quasi, voluptates perspiciatis iste at tempore quod, dolor sit dolore cumque facilis tempora aperiam voluptatem facere officiis libero autem reiciendis assumenda. Blanditiis perferendis voluptas maxime dolor praesentium!
        Consectetur voluptatibus eaque at nesciunt id odio, esse ratione harum magnam, dolorem nisi maiores deserunt dolore voluptatem earum iure corporis nulla amet molestias doloremque? Nemo beatae ipsam provident commodi odio!
        Temporibus enim accusamus similique nisi maxime obcaecati quae quasi ratione voluptates unde. Et ut itaque voluptas quisquam necessitatibus, quasi sed tempore dignissimos, a, deserunt laborum animi non at est consequatur.
        Ea cum quaerat eveniet? Aperiam nesciunt veritatis quam, illum eveniet nostrum debitis corrupti, voluptatum animi perferendis rem? Illum nesciunt perferendis non culpa corporis magni soluta autem ut tempore nobis? Modi.
        Nisi enim, beatae officiis culpa itaque cumque veritatis facere ab quae praesentium eveniet? Optio vitae ex consequatur iure quibusdam, autem est odit reprehenderit necessitatibus voluptatibus quos illum nostrum unde provident.
        Aliquam sed iste maxime maiores voluptate error harum, excepturi laborum qui vitae? Laudantium omnis minus velit temporibus odio delectus voluptatibus sint, maxime ex natus ut autem id cum rem ipsum.
        Quis officia nihil quisquam quibusdam veritatis incidunt recusandae laborum labore soluta voluptates, autem similique. Eos exercitationem, recusandae non officiis ad ipsum a officia harum maxime totam sapiente similique eius commodi.
        Et eum non a cum modi? Nam suscipit distinctio ut in neque amet optio? Minima, ipsum voluptate aspernatur sed officia temporibus nesciunt! Id et accusantium adipisci soluta ipsa, dolorem ullam.
        Alias voluptate quam consectetur tenetur eaque perspiciatis expedita eligendi natus repellat provident culpa nam sed, autem dolor atque explicabo. Maiores incidunt distinctio dicta porro a laboriosam corrupti pariatur quaerat ipsa?
        Delectus beatae porro doloribus, deserunt accusamus exercitationem placeat alias illo vitae dolor cumque odit, omnis id amet sit est, magni itaque quae? Culpa porro eaque, veritatis nihil odit delectus. Assumenda.
      </div>
    </div>
  )   
};

export default Shop;